# Generated by Django 3.0.8 on 2020-07-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_n', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
