# Generated by Django 3.0.8 on 2020-07-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='n_type',
            field=models.CharField(choices=[('pub', 'public'), ('pri', 'private')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
